---
title: "Álgebra Linear Computacional"
---

## Informações sobre o curso
- Curso sobre a teoria, as aplicações e as considerações práticas de se implementar e executar operações matriciais em computadores usando dados reais
    - Foco: como realizar cálculos matriciais com velocidade e precisão aceitáveis?
- É o mesmo que "Análise Numérica", só mudou o nome?
    - Não, embora alguns tópicos da ementa sejam comuns
- É álgebra linear avançada?
    - Não, alguns conceitos de AL serão revisados ao longo do semestre
    - Eu diria que é mais próximo de uma Álgebra Linear aplicada à Computação

## Horário e sala
- Turmas: TTZ1, TN1 e TN
- Terças e quintas das 14:55 às 16:35
- Sala 2013


## Ementa
Eliminação Gaussiana. Decomposição LU. Decomposição espectral. Decomposição SVD. Condicionamento. Decomposição QR. Tópicos em análise numérica.

## Objetivos
- Revisar conceitos fundamentais de Álgebra Linear
- Fornecer ao aluno métodos necessários à resolução numérica de problemas que envolvam decomposição de matrizes
- Familiarizar e motivar o aluno com aplicações práticas em computação dos métodos vistos ao longo do curso
- Manipular dados em um ambiente científico

## Cronograma


| Aula | Data     | Conteúdo       |
|:--:|:------:|:---------------|
| 1|23/08/22|[Vetores, Matrizes, Espaços Vetoriais e Espaço Coluna](https://heitorramos.github.io/Slides_ALC/Aula01.html)|
|2|25/08/22| [Vetores, Matrizes, Espaços Vetoriais e Espaço Coluna - II](https://heitorramos.github.io/Slides_ALC/Aula01.html)|
|3|30/08/22|[Multiplicando e Fatorando Matrizes](https://heitorramos.github.io/Slides_ALC/Aula02.html)|
|4|01/09/22|[Quatro subspaços fundamentais](https://heitorramos.github.io/Slides_ALC/Aula03.html)|
|5|06/09/22|[Autovalores e Autovetores](https://heitorramos.github.io/Slides_ALC/Aula04.html) |
|6|08/09/22|[Matrizes ortogonais <!-- colocar também matrizes positivas definidas-->](https://heitorramos.github.io/Slides_ALC/Aula05.html)|
|7|13/09/22|[Normas de Vetores e Matrizes](https://heitorramos.github.io/Slides_ALC/Aula06.html)| 
|8|15/09/22|[Normas de Vetores e Matrizes II](https://heitorramos.github.io/Slides_ALC/Aula07.html)|
|9|20/09/22|[Matrizes Definidas Positivas e Semidefinidas](https://heitorramos.github.io/Slides_ALC/Aula08.html)|
|10|22/09/22|[Page Rank](https://heitorramos.github.io/Slides_ALC/Aula09.html)|
|11|27/09/22|[Page Rank II](https://heitorramos.github.io/Slides_ALC/Aula09.html)|
|12|29/09/22|[SVD e aproximação de matrizes](https://heitorramos.github.io/Slides_ALC/Aula11.html)|
|13|04/10/22|[Decomposição em valores Singulares](https://heitorramos.github.io/Slides_ALC/Aula10.html)|
|14|06/10/22|[Decomposição em valores Singulares II](https://heitorramos.github.io/Slides_ALC/Aula10.html)|
|15|11/10/22|[PCA I](https://heitorramos.github.io/Slides_ALC/Aula12.html)|
|16|13/10/22|[PCA II](https://heitorramos.github.io/Slides_ALC/Aula13.html)|
|17|18/10/22|[Remoção de viés com PCA](https://heitorramos.github.io/Slides_ALC/Aula14.html)|
|18|20/10/22|[Regressão Linear](https://heitorramos.github.io/Slides_ALC/Aula15.html)|
|19|25/10/22|[Regressão Linear Múltipla](https://heitorramos.github.io/Slides_ALC/Aula16.html)|
|20|27/10/22|[Decomposição QR/Ajuste via Decomposição em Valores Singulares](https://heitorramos.github.io/Slides_ALC/Aula17.html)|
|21|01/11/22|[Introdução a Sistemas Lineares / Sistemas Triangulares / Eliminação de Gauss](https://heitorramos.github.io/Slides_ALC/Aula18.html)|
|23|03/11/22|[Prova 1]{.vermelho}|
|22|08/11/22|[Decomposição LU e Cholesky](https://heitorramos.github.io/Slides_ALC/Aula19.html)|
|x|10/11/22|Não haverá aula|
|24|17/11/22|[Decomposição Cholesky)](https://heitorramos.github.io/Slides_ALC/Aula19.html)|
|25|22/11/22|[Métodos Iterativos Estacionários - Jacobi](https://heitorramos.github.io/Slides_ALC/Aula20.html)|
|x|24/11/22|Jogo do Brasil|
|26|29/11/22|[Métodos Iterativos Estacionários - Gauss Seidel e Sobre-Relaxação Sucessiva](https://heitorramos.github.io/Slides_ALC/Aula20.html)|
|27|01/12/22|[Métodos Iterativos Estacionários - Análise de Convergência](https://heitorramos.github.io/Slides_ALC/Aula21.html)|
|28|06/12/22|[Análise de Erros na Solução de Sistemas Lineares](https://heitorramos.github.io/Slides_ALC/Aula22.html)|
|29|08/12/22|[Prova 2]{.vermelho}|
|30|15/12/22|Prova Suplementar|
|30|20/12/22|Exame Especial|


## Dinâmica
- Aulas téóricas e alguns exemplos de aplicação dos conceitos 


## Avaliação de Aprendizagem
- Prova 1 (30 pontos)
- Prova 2 (30 pontos)
- Listas de exercícios teóricos e de programação (40 pontos) (a serem entregues ao longo do semestre)

## Material de apoio
- Moodle (slides e outros materiais) 
- Vídeos
- Software: Python


## Bibliografia
- Trefethen, L. N. & Bau III, D. Numerical Linear Algebra. Vol. 50. SIAM, 1997 
- Strang, Gilbert. Linear Algebra and Learning from Data. Wellesley-Cambridge Press, 2019.
- Ferreira Campos, filho, Frederico. Algoritmos Numéricos: uma abordagem moderna de Cálculo Numérico. 3a Edição. LCT, 2018.
