---
title: "Students"
---

## Current Students

:::{.callout-note icon="false"}
## Ph.D Candidate
- Isadora Cardoso Pereira da Silva 
- Pedro Henrique de Souza Barros 
- Eduarda Tatiane Caetano Chagas 
- Ekler Paulino de Mattos 
:::

:::{.callout-note icon="false"}
## M.Sc Candidate
- Diego Haji Carvalho Campos
- Túlio Nunes Polido Lopes
:::

:::{.callout-note icon="false"}
## Undergrad Students
- Rodrigo Pierre Fernandes Felizardo
- Gabriel de Souza Gomes
- Izabela Esber Xavier
- Manuela Monteiro Fernandes de Oliveira
:::

## Past Graduate Students

:::{.callout-note icon="false"}
## Ph.D
- João Batista Borges Neto
:::

:::{.callout-note icon="false"}
## M.Sc
- Giovanna Ávila Riqueti
- Eduarda Tatiane Caetano Chagas
- Pedro Henrique Silva Souza Barros
- Isadora Cardoso Pereira da Silva
- Daniel Kazuyuki Fugii Matsumoto
- Keila Barbosa Costa
- Vilker Tenório Cabral Lobo
- Marcelo Queiroz de Assis Oliveira
- Thiago Montenegro Uchôa
- Alyson Leandro Costa Oliveira
- Eduardo Mucelli Rezende de Oliveira
:::

## Past Undergrad Students 

:::{.callout-note icon="false"}
## Scientific Research
- Marco Tulio de Pinho Tavares Tristao
- Rafaela de Fatima Silva Alexandre
- Morgana Gabi Nascimento Ferreira Souza Gomes 
- Ananda de Oliveira Lopes
- Igor Patricio dos Santos
- Bruno Marques Barbosa
- Pedro Henrique de Souza Barros
- Anthony Emanoel de Albuquerque Jatoba
- Marcos Vinícius Santos Costa
- Isadora Cardoso Pereira da Silva
- Tarciso Ferreira da Silva Filho
- Matheus Nascimento Tavares
- Caio Cesar do Santos Nunes
- Gilberto Carvalho Fernandes Silva
- Bruno Gabriel Cavalcante Lima
- Rebeca Buarque de Araujo Barros
- Ana Geórgia de Souza Silva Gama Pereira
:::

:::{.callout-note icon="false"}
## Bachelor Monography
- Isadora Cardoso Pereira da Silva
- Vilker Tenório Cabral Lobo
- Wesley Lino Albuquerque da Silva
- Felipe Buarque de Queiroz
- Alyson Leandro Costa Oliveira
- Hugo Estanislau Soares Galindo
- André Ferreira Alécio Gomes
- Luiz Josué da Silva Filho
- Leandro Melo de Sales
- Bruno Alburquerque de Oliveira
- Fabiano Andrade Costa
- Hudson Coelho Esmeraldo
- Arquilene Silva Cunha
- Marcelo Queiroz de Assis Oliveira
- Sidney Pontes Viana
- Fábio José Rodrigues Pinheiro
:::